python tools/analysis_tools/analyze_logsBenz.py cal_train_time work_dirs/New_OCT/FasterRCNN_R101_CellNuc/20221203_171924.log.json
python tools/analysis_tools/get_flopsBenz.py work_dirs/New_OCT/FasterRCNN_R101_CellNuc/faster_rcnn_r101_CellNucNo.py
python tools/analysis_tools/analyze_logsBenz.py cal_train_time work_dirs/New_OCT/FasterRCNN_R50_CellNuc/20221203_190102.log.json
python tools/analysis_tools/get_flopsBenz.py work_dirs/New_OCT/FasterRCNN_R50_CellNuc/faster_rcnn_r50_CellNucNo.py
python tools/analysis_tools/analyze_logsBenz.py cal_train_time work_dirs/New_OCT/ATSS_R101_CellNuc/20221203_171851.log.json
python tools/analysis_tools/get_flopsBenz.py work_dirs/New_OCT/ATSS_R101_CellNuc/atss_r101_CellNucNo.py
python tools/analysis_tools/analyze_logsBenz.py cal_train_time work_dirs/New_OCT/ATSS_R50_CellNuc/20221203_185223.log.json
python tools/analysis_tools/get_flopsBenz.py work_dirs/New_OCT/ATSS_R50_CellNuc/atss_r50_CellNucNo.py
python tools/analysis_tools/analyze_logsBenz.py cal_train_time work_dirs/New_OCT/MaskRCNN_R101_CellNuc/20221203_202419.log.json
python tools/analysis_tools/get_flopsBenz.py work_dirs/New_OCT/MaskRCNN_R101_CellNuc/mask_rcnn_r101_CellNucNo.py
python tools/analysis_tools/analyze_logsBenz.py cal_train_time work_dirs/New_OCT/MaskRCNN_R50_CellNuc/20221204_005007.log.json
python tools/analysis_tools/get_flopsBenz.py work_dirs/New_OCT/MaskRCNN_R50_CellNuc/mask_rcnn_r50_CellNucNo.py
python tools/analysis_tools/analyze_logsBenz.py cal_train_time work_dirs/New_OCT/YoloV3_DarkNet_CellNuc/20221204_025606.log.json
python tools/analysis_tools/get_flopsBenz.py work_dirs/New_OCT/YoloV3_DarkNet_CellNuc/yolov3_d53_416_CellNucNo.py
python tools/analysis_tools/analyze_logsBenz.py cal_train_time work_dirs/New_OCT/YoloV3_Mobilenet_CellNuc/20221204_034455.log.json
python tools/analysis_tools/get_flopsBenz.py work_dirs/New_OCT/YoloV3_Mobilenet_CellNuc/yolov3_mobilenetv2_CellNucNo.py
